#!/usr/bin/env bash

set -euo pipefail

CONTAINER_TAG=localhost/dnf-rebuild
REBUILD_PATH=/etc/dnf/rebuild
CACHEDIR=/var/cache/libdnf5

action=rebuild
upgrade=false
for i in "$@"; do
  case $i in
    --upgrade)
      upgrade=true
      shift
      ;;
    --init)
      action=init
      shift
      ;;
    -*|--*)
      echo "Unknown option $i"
      exit 1
      ;;
    *)
      ;;
  esac
done

init () {
    # Set up template with Containerfile pieces under /etc/dnf/rebuild
    mkdir -p "$REBUILD_PATH"

    status="$(bootc status --format=json)"
    transport=$(jq -r '.spec.image.transport' <<< "$status")
    if [[ "$transport" != "registry" ]]; then
        echo "Error: spec.image.transport is not 'registry' (got: $transport)" >&2
        exit 1
    fi
    base="$(jq -r '.spec.image.image' <<< "$status")"
    arch="$(dnf repoquery --installed --queryformat '%{arch}' dnf5)"

    cat > "$REBUILD_PATH/Containerfile.in" <<EOF 
# This file is generated by dnf-rebuild! Do not modify!

#include "Containerfile.base"

COPY . "$REBUILD_PATH"

WORKDIR "$REBUILD_PATH"

# For now, use nightly DNF5 and libpkgmanifest
RUN dnf install -y 'dnf5-command(copr)' && \
    dnf copr enable rpmsoftwaremanagement/dnf-nightly -y && \
    dnf copr enable rpmsoftwaremanagement/libpkgmanifest-nightly -y && \
    dnf distro-sync --from-repo copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly,copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:libpkgmanifest-nightly -y && \
    dnf install -y --from-repo copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf-nightly 'dnf5-command(manifest)' && \
    dnf install -y 'dnf5-command(manifest)'

RUN dnf manifest resolve --use-host-repos --disableplugin=local --use-system

RUN dnf manifest install -y --disableplugin=local --setopt=keepcache=true --setopt=destdir="$CACHEDIR"

#include "Containerfile.postinstall"
EOF

    [ -f "$REBUILD_PATH/Containerfile.base" ] || cat > "$REBUILD_PATH/Containerfile.base" <<EOF
FROM quay.io/fedora/fedora-bootc:rawhide
EOF

    [ -f "$REBUILD_PATH/Containerfile.postinstall" ] || cat > "$REBUILD_PATH/Containerfile.postinstall" <<EOF 
# This section will be executed after installing packages with DNF.
EOF

    [ -f "REBUILD_PATH/rpms.in.yaml" ] || cat > "$REBUILD_PATH/rpms.in.yaml" <<EOF
contentOrigin:
    repos:
packages:
arches:
    - $arch
EOF

    echo Created "$REBUILD_PATH" based on "$base"
}

rebuild () {
    cd "$REBUILD_PATH" || {
        echo "$REBUILD_PATH does not exist. Run dnf-rebuild --init first."
        exit 1
    }

    if [[ -n "$upgrade" ]]; then
        pull="always"
    else
        pull="never"
    fi
    podman build --file Containerfile.in --tag "$CONTAINER_TAG" --volume "$CACHEDIR:$CACHEDIR":z --pull="$pull" .
    id="$(podman inspect --format '{{.Id}}' "$CONTAINER_TAG":latest)"

    # With https://github.com/bootc-dev/bootc/issues/20 we might no longer need `--transport containers-storage`
    bootc switch --transport containers-storage "$id"
}

case "$action" in
    rebuild)
        rebuild
        ;;
    init)
        init
        ;;
    *)
        echo "Unknown action $action"
        exit 1
        ;;
esac
